[project]
name = "chimera"
version = "0.1.0"
description = "Autonomous Influencer Network"
dependencies = [
    "pytest>=9.0.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
